# Generated by Django 5.1.4 on 2026-06-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
